# Generated by Django 4.1.5 on 2023-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productlist',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_category', models.CharField(max_length=200)),
                ('Product_price', models.CharField(max_length=200)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
